
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Color2048 : Luban.BeanBase
{
    public Color2048(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Colors = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); Colors.Add(_e0);}}
    }

    public static Color2048 DeserializeColor2048(ByteBuf _buf)
    {
        return new Color2048(_buf);
    }

    public readonly int Id;
    public readonly System.Collections.Generic.List<string> Colors;
   
    public const int __ID__ = -311141627;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "colors:" + Luban.StringUtil.CollectionToString(Colors) + ","
        + "}";
    }
}

}

