
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class Color2048Config
{
    private readonly System.Collections.Generic.Dictionary<int, Color2048> _dataMap;
    private readonly System.Collections.Generic.List<Color2048> _dataList;
    
    public Color2048Config(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Color2048>();
        _dataList = new System.Collections.Generic.List<Color2048>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Color2048 _v;
            _v = Color2048.DeserializeColor2048(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Color2048> DataMap => _dataMap;
    public System.Collections.Generic.List<Color2048> DataList => _dataList;

    public Color2048 GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Color2048 Get(int key) => _dataMap[key];
    public Color2048 this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

