
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    #region The Tables

    private Color2048Config m_Color2048Config;
    public Color2048Config Color2048Config 
    {
        get
        {
            if (m_Color2048Config == null)
            {
                m_Color2048Config = new Color2048Config(defaultLoader("Color2048Config"));
                m_Color2048Config.ResolveRef(this);
            }
            return m_Color2048Config;
        }
        set
        {
            m_Color2048Config = value;
            m_Color2048Config.ResolveRef(this);
        }
    }
    private LanguageConfig m_LanguageConfig;
    public LanguageConfig LanguageConfig 
    {
        get
        {
            if (m_LanguageConfig == null)
            {
                m_LanguageConfig = new LanguageConfig(defaultLoader("LanguageConfig"));
                m_LanguageConfig.ResolveRef(this);
            }
            return m_LanguageConfig;
        }
        set
        {
            m_LanguageConfig = value;
            m_LanguageConfig.ResolveRef(this);
        }
    }

    #endregion

    System.Func<string, ByteBuf> defaultLoader;

    public Tables(System.Func<string, ByteBuf> loader)
    {
        SetDefaultLoader(loader);
        Init();
    }
    
    public void SetDefaultLoader(System.Func<string, ByteBuf> loader)
    {
        defaultLoader = null;
        defaultLoader = loader;
    }

    //public partial void Init();

    public void Init(){}
}

}
